# Server Details
server:
 port: 8090
 ssl:
  key-store: classpath:keystore.p12
  key-store-password: 12345678
  key-store-type: pkcs12
  key-alias: hikSelfSsl
  key-password: 12345678
  
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

hikvision:
 appKey: 28729388
 appSecret: gUmLhDisMFBQxKAWXLB8
 artemisPath: /artemis
 httpOrHttps: http
 faceorder:
  host: 202.55.92.163
  port: 9016
  url: /api/visitor/v1/orderWithFace
 qap:
  host: 202.55.92.163
  port: 9016
  url: /api/acs/v1/door/events
 gpg:
  host: 202.55.92.163
  port: 9016
  url: /api/visitor/v1/getPrivilegeGroup
  
logging:
  level:
    org.springframework: ERROR
    com.hik.mw.controller: DEBUG
    com.hikvision.artemis.sdk : INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: E:/Project/hiklogs/hikMw.log